### ISSUE TITLE
MTProxy代理问题·

### ISSUE THREAD

**Issue by langhun** [SuMaiKaDe/bot#15]
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/ql/jbot/__init__.py", line 67, in <module>
    jdbot = TelegramClient('bot', api_id, api_hash, connection=connectionType,
  File "/usr/lib/python3.8/site-packages/telethon/client/auth.py", line 133, in start
    else self.loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/lib/python3.8/site-packages/telethon/client/auth.py", line 140, in _start
    await self.connect()
  File "/usr/lib/python3.8/site-packages/telethon/client/telegrambaseclient.py", line 513, in connect
    if not await self._sender.connect(self._connection(
  File "/usr/lib/python3.8/site-packages/telethon/network/mtprotosender.py", line 127, in connect
    await self._connect()
  File "/usr/lib/python3.8/site-packages/telethon/network/mtprotosender.py", line 227, in _connect
    connected = await self._try_connect(attempt)
  File "/usr/lib/python3.8/site-packages/telethon/network/mtprotosender.py", line 277, in _try_connect
    await self._connection.connect(timeout=self._connect_timeout)
  File "/usr/lib/python3.8/site-packages/telethon/network/connection/connection.py", line 244, in connect
    await self._connect(timeout=timeout, ssl=ssl)
  File "/usr/lib/python3.8/site-packages/telethon/network/connection/tcpmtproxy.py", line 106, in _connect
    await super()._connect(timeout=timeout, ssl=ssl)
  File "/usr/lib/python3.8/site-packages/telethon/network/connection/connection.py", line 237, in _connect
    self._init_conn()
  File "/usr/lib/python3.8/site-packages/telethon/network/connection/connection.py", line 386, in _init_conn
    self._obfuscation = self.obfuscated_io(self)
  File "/usr/lib/python3.8/site-packages/telethon/network/connection/tcpmtproxy.py", line 28, in __init__
    self._decrypt) = self.init_header(
  File "/usr/lib/python3.8/site-packages/telethon/network/connection/tcpmtproxy.py", line 42, in init_header
    **raise ValueError(
ValueError: MTProxy secret must be a hex-string representing 16 bytes**

一直都是这个错误，请问怎么解决

**Comment by SuMaiKaDe** [comment]
@langhun 部分mtp代理这个库不支持

**Comment by langhun** [comment]
> @langhun 部分mtp代理这个库不支持

那请问应该怎么解决？有推荐的安装么？

**Comment by SuMaiKaDe** [comment]
@langhun 暂无解决办法，换代理吧

**Comment by langhun** [comment]
> @langhun 暂无解决办法，换代理吧

好的，谢谢回答
