### ISSUE TITLE
bot机器人无法激活？

### ISSUE THREAD

**Issue by photonmang** [SuMaiKaDe/bot#22]
新注册的bot机器只要运行就提示没有userID，已经对接过的ID可以对接成功，请问是哪里的问题呢？

2021-08-12 15:59:52,679-asyncio-ERROR=> [default_exception_handler] Task exception was never retrieved
future: <Task finished name='Task-10' coro=<hello() done, defined at /jd/jbot/__main__.py:64> exception=ValueError('Could not find the input entity for PeerUser(user_id=1934278299) (PeerUser). Please read https://docs.telethon.dev/en/latest/concepts/entities.html to find out more details.')> 
Traceback (most recent call last):
  File "/jd/jbot/__main__.py", line 69, in hello
    await jdbot.send_message(chat_id, f'{str(word)}\n\n\t{info}', link_preview=False)
  File "/usr/lib/python3.8/site-packages/telethon/client/messages.py", line 767, in send_message
    entity = await self.get_input_entity(entity)
  File "/usr/lib/python3.8/site-packages/telethon/client/users.py", line 461, in get_input_entity
    raise ValueError(
ValueError: Could not find the input entity for PeerUser(user_id=1934278299) (PeerUser). Please read https://docs.telethon.dev/en/latest/concepts/entities.html to find out more details.

**Comment by SuMaiKaDe** [comment]
1934278299 这是你的tg的id吗
