### ISSUE TITLE
python3 -m jbot出错

### ISSUE THREAD

**Issue by beyond120** [SuMaiKaDe/bot#47]
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/ql/jbot/__init__.py", line 1, in <module>
    from telethon import TelegramClient, connection
  File "/usr/lib/python3.8/site-packages/telethon/__init__.py", line 1, in <module>
    from .client.telegramclient import TelegramClient
  File "/usr/lib/python3.8/site-packages/telethon/client/__init__.py", line 23, in <module>
    from .auth import AuthMethods
ModuleNotFoundError: No module named 'telethon.client.auth'

**Comment by freefly22** [comment]
跟你一样的问题，解决了吗？
