### ISSUE TITLE
新注册的TG，始终无法运行

### ISSUE THREAD

**Issue by alastone** [SuMaiKaDe/bot#57]
2022-02-27 23:15:12,260-telethon.network.mtprotosender-ERROR=> [send] Request caused struct.error: 'I' format requires 0 <= number <= 4294967295: GetUsersRequest(id=[InputUser(user_id=5299254924, access_hash=0)]) 
2022-02-27 23:15:12,261-asyncio-ERROR=> [default_exception_handler] Task exception was never retrieved
future: <Task finished name='Task-9' coro=<new_ver() done, defined at /jd/jbot/__main__.py:21> exception=error("'I' format requires 0 <= number <= 4294967295")> 
Traceback (most recent call last):
  File "/jd/jbot/__main__.py", line 37, in new_ver
    await jdbot.send_message(chat_id, f'[机器人上新了](https://github.com/SuMaiKaDe/jddockerbot/tree/master)\n{botlog}\n运行日志为log/bot/run.log\n\n\t{info}', link_preview=False)
  File "/usr/lib/python3.8/site-packages/telethon/client/messages.py", line 767, in send_message
    entity = await self.get_input_entity(entity)
  File "/usr/lib/python3.8/site-packages/telethon/client/users.py", line 440, in get_input_entity
    users = await self(functions.users.GetUsersRequest([
  File "/usr/lib/python3.8/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/usr/lib/python3.8/site-packages/telethon/client/users.py", line 58, in _call
    future = sender.send(request, ordered=ordered)
  File "/usr/lib/python3.8/site-packages/telethon/network/mtprotosender.py", line 176, in send
    state = RequestState(request)
  File "/usr/lib/python3.8/site-packages/telethon/network/requeststate.py", line 17, in __init__
    self.data = bytes(request)
  File "/usr/lib/python3.8/site-packages/telethon/tl/tlobject.py", line 194, in __bytes__
    return self._bytes()
  File "/usr/lib/python3.8/site-packages/telethon/tl/functions/users.py", line 72, in _bytes
    b'\x15\xc4\xb5\x1c',struct.pack('<i', len(self.id)),b''.join(x._bytes() for x in self.id),
  File "/usr/lib/python3.8/site-packages/telethon/tl/functions/users.py", line 72, in <genexpr>
    b'\x15\xc4\xb5\x1c',struct.pack('<i', len(self.id)),b''.join(x._bytes() for x in self.id),
  File "/usr/lib/python3.8/site-packages/telethon/tl/types/__init__.py", line 11564, in _bytes
    struct.pack('<I', self.user_id),
struct.error: 'I' format requires 0 <= number <= 4294967295

**Comment by SuMaiKaDe** [comment]
@alastone 没有更新telethon

**Comment by alastone** [comment]
好的  谢谢大佬，我试试

**Comment by alastone** [comment]
@SuMaiKaDe 还是同样的错误

**Comment by alastone** [comment]
> @alastone 没有更新telethon

同样报错

**Comment by SuMaiKaDe** [comment]
@alastone 这个错误就是这个引起的 你看一下你的telethon的版本吧

**Comment by alastone** [comment]
> telethon

root@jd:/jd# python3 -c "import telethon; print(telethon.__version__)"
1.21.1
这个版本可以吗

**Comment by SuMaiKaDe** [comment]
@alastone 不行 1.24 至少

**Comment by alastone** [comment]
> @alastone 不行 1.24 至少

小白求一条升级命令

**Comment by alastone** [comment]
> > @alastone 不行 1.24 至少
> 
> 小白求一条升级命令

谢谢大佬的耐心解答，解决了

**Comment by windowlife** [comment]
> 
docker exec -it qinglong bash -c "pip3 install --upgrade telethon"

**Comment by windowlife** [comment]
升级了telethon，还是报同一个错误
